services:
  - type: web
    name: dental-app
    runtime: python3
    # Option 1: Gunicorn (Recommended for production)
    # startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    # Option 2: Simple Python3 (Alternative - less robust)
    startCommand: python3 app.py
    plan: starter
    buildCommand: pip install -r requirements.txt
    autoDeploy: true
    env:
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: dental-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false  # You'll set this manually in Render dashboard

  - type: pgsql
    name: dental-db
    databaseName: dental_practice
    user: dental_user
    plan: starter 